In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Provideniya,RU,2021-04-03 19:13:16,64.3833,-173.3000,6.21,92,100,10.00
1,1,Dayong,CN,2021-04-03 19:13:17,25.0209,118.2898,69.80,88,90,6.71
2,2,Rikitea,PF,2021-04-03 19:13:17,-23.1203,-134.9692,76.78,68,91,16.89
3,3,Taoudenni,ML,2021-04-03 19:13:17,22.6783,-3.9836,95.61,7,100,9.95
4,4,Sao Filipe,CV,2021-04-03 19:13:18,14.8961,-24.4956,74.97,68,11,8.25

In [5]:
#Get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [10]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [11]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [16]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
print(fig)

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
print(fig)

Figure(layout=FigureLayout(height='420px'))

In [20]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
print(fig)

Figure(layout=FigureLayout(height='420px'))

In [21]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
print(fig)

Figure(layout=FigureLayout(height='420px'))

In [22]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [23]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Rikitea,PF,2021-04-03 19:13:17,-23.1203,-134.9692,76.78,68,91,16.89
9,9,Souillac,MU,2021-04-03 19:13:19,-20.5167,57.5167,80.60,89,40,4.61
11,11,Diffa,NE,2021-04-03 19:13:19,13.3154,12.6113,82.22,9,1,6.82
15,15,Kapaa,US,2021-04-03 19:13:20,22.0752,-159.3190,75.20,69,40,17.27
19,19,Puerto Ayora,EC,2021-04-03 19:13:07,-0.7393,-90.3518,82.40,74,20,8.05
20,20,Cam Ranh,VN,2021-04-03 19:13:21,11.9214,109.1591,78.80,83,20,4.61
24,24,Inirida,CO,2021-04-03 19:13:22,3.8653,-67.9239,88.18,59,94,1.45
27,27,Kavieng,PG,2021-04-03 19:13:23,-2.5744,150.7967,81.72,75,38,3.89
30,30,Faanui,PF,2021-04-03 19:13:24,-16.4833,-151.7500,81.77,71,22,6.13
34,34,Acari,PE,2021-04-03 19:13:25,-15.4311,-74.6158,83.52,53,98,10.00

In [26]:
preferred_cities_df.count()

City_ID       201
City          201
Country       201
Date          201
Lat           201
Lng           201
Max Temp      201
Humidity      201
Cloudiness    201
Wind Speed    201
dtype: int64

In [25]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
2        Rikitea      PF     76.78 -23.1203 -134.9692
9       Souillac      MU     80.60 -20.5167   57.5167
11         Diffa      NE     82.22  13.3154   12.6113
15         Kapaa      US     75.20  22.0752 -159.3190
19  Puerto Ayora      EC     82.40  -0.7393  -90.3518
20      Cam Ranh      VN     78.80  11.9214  109.1591
24       Inirida      CO     88.18   3.8653  -67.9239
27       Kavieng      PG     81.72  -2.5744  150.7967
30        Faanui      PF     81.77 -16.4833 -151.7500
34         Acari      PE     83.52 -15.4311  -74.6158

In [36]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
# Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [37]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
2,Rikitea,PF,76.78,-23.1203,-134.9692,Pension Maro'i
9,Souillac,MU,80.60,-20.5167,57.5167,Shanti Maurice Resort & Spa
11,Diffa,NE,82.22,13.3154,12.6113,ProDAF/Diffa
15,Kapaa,US,75.20,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
19,Puerto Ayora,EC,82.40,-0.7393,-90.3518,Finch Bay Galapagos Hotel
20,Cam Ranh,VN,78.80,11.9214,109.1591,OYO 598 Peony Hotel
24,Inirida,CO,88.18,3.8653,-67.9239,Fuente del Guania Hotel de Lujo
27,Kavieng,PG,81.72,-2.5744,150.7967,Nusa Island Retreat
30,Faanui,PF,81.77,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
34,Acari,PE,83.52,-15.4311,-74.6158,HOSPEDAJE XIMENA

In [40]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
print(fig)

Figure(layout=FigureLayout(height='420px'))

In [41]:
#Adding markers

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [42]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [43]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
print(fig)

Figure(layout=FigureLayout(height='420px'))